
  - name: Install python3
    yum:
      name: python3
      state: present

  - name: Install docker with Python 3
    pip:
      name: docker
      executable: pip3
    vars:
      ansible_python_interpreter: /usr/bin/python3




  - name: Run Front
    vars:
      ansible_python_interpreter: /usr/bin/python3
    docker_container:
      name: front
      image: jaykabonk/devops-frontend:latest
      recreate: true
      pull: true
      networks:
        - name: app-network
      ports:
        - "80:80"
      env:
        VUE_APP_API_URL: "yoann.cathelain.takima.cloud:8080"