all:
        vars:
                ansible_user: "{{ ansible_user }}"
                ansible_ssh_private_key_file: "{{ ansible_private_key_path }}"

        children:
                prod:
                        hosts: "centos@yoann.cathelain.takima.cloud"
