---
# tasks file for roles/network

  - name: Install python3
    yum:
      name: python3
      state: present

  - name: Install docker with Python 3
    pip:
      name: docker
      executable: pip3
    vars:
      ansible_python_interpreter: /usr/bin/python3

  - name: Create a network
    docker_network:
      name: app-network
    vars:
      ansible_python_interpreter: /usr/bin/python3