# tasks file for roles/app
  - name: Install python3
    yum:
      name: python3
      state: present

  - name: Install docker with Python 3
    pip:
      name: docker
      executable: pip3
    vars:
      ansible_python_interpreter: /usr/bin/python3



  - name: Create Backend container
    vars:
        ansible_python_interpreter: /usr/bin/python3

    docker_container:
      name: backend
      networks:
        - name: app-network
      image: jaykabonk/backend-tp1
      recreate: true
      pull: true
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://database/aled
        SPRING_DATASOURCE_USERNAME: aled
        SPRING_DATASOURCE_PASSWORD: aled
