# tasks file for roles/proxy

  - name: Install python3
    yum:
      name: python3
      state: present

  - name: Install docker with Python 3
    pip:
      name: docker
      executable: pip3
    vars:
      ansible_python_interpreter: /usr/bin/python3


  - name: Create HTTP container
    vars:
      ansible_python_interpreter: /usr/bin/python3
    docker_container:
      name: devops-http
      networks:
        - name: app-network
      image: jaykabonk/httpd-tp1
      recreate: true
      pull: true
      ports:
        - 8080:80
      